name: Android build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Set-up a temporary keystore for signing
      run: |
        echo y | keytool -genkeypair -dname "cn=GitHub CI, ou=JavaSoft, o=Sun, c=US" -alias alias -keypass android -keystore ci.keystore -storepass android -validity 20000
        echo RELEASE_STORE_FILE=`pwd`/ci.keystore > ~/.gradle/gradle.properties
        echo RELEASE_STORE_PASSWORD=android >> ~/.gradle/gradle.properties
        echo RELEASE_KEY_ALIAS=alias >> ~/.gradle/gradle.properties
        echo RELEASE_KEY_PASSWORD=android >> ~/.gradle/gradle.properties
    - name: Build with Gradle
      run: ./gradlew build

